# Generated by Django 4.2.21 on 2025-05-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_produto_slug_alter_produto_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='titulo',
        ),
        migrations.AddField(
            model_name='categoria',
            name='nome',
            field=models.CharField(default='Sem nome', max_length=100),
        ),
    ]
